# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: wiamlmsapplication
services:
  app:
    image: wiamlmsapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/wiamlmsapplication?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
      - SPRING_LIQUIBASE_URL=jdbc:mysql://mysql:3306/wiamlmsapplication?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    ports:
      - 127.0.0.1:8787:8787
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8787/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      mysql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
  mysql:
    extends:
      file: ./mysql.yml
      service: mysql
  elasticsearch:
    extends:
      file: ./elasticsearch.yml
      service: elasticsearch
